### ISSUE TITLE
Installation/use

### ISSUE THREAD

**Issue by SheriffOfNotts** [giovannicoppola/Meeting-Notes#1]
Please can you let me know how to install this - this is exactly what I've been looking for! Thank you.

**Comment by giovannicoppola** [comment]
I launch this script with Alfred, but other launchers can be used (Quicksilver etc), or Automator. Do you use any of these?

**Comment by SheriffOfNotts** [comment]
Hi, thanks for your reply. I’ve used Automator for a folder action. Are you able to tell me how to use Automator for this. I also understudy DT3 uses apple script for a lot of it’s add on functionality?

Really appreciate your help. 

Regards

**Comment by SheriffOfNotts** [comment]
I've managed to get it working :) It's fab :)

Is there any to additional capture the organiser of the meeting?

Thanks again.

**Comment by giovannicoppola** [comment]
you can add 
`set theOrganizer to the organizer of calendarEvent`
around lines 25-27, then add something like 
`"Organized by" & theOrganizer` 
in the `content` section on line 51

**Comment by SheriffOfNotts** [comment]
Thanks Giovanni, this will save lots of re-keying..

**Comment by SheriffOfNotts** [comment]
All working :)

Not wishing to push my luck lol, but is there a way of using this info to fill in a DT3 template?

Regards

**Comment by giovannicoppola** [comment]
not too familiar with templates... can look into it

**Comment by SheriffOfNotts** [comment]
That would be amazing, thank you.

Could the fields in the enclosed template be populated by the script?

Do you have "buy me a coffee" link?

Regards
[Meeting Notes Template.zip](https://github.com/giovannicoppola/Meeting-Notes/files/6694512/Meeting.Notes.Template.zip)

**Comment by giovannicoppola** [comment]
this is an RTF file, a quick google search seems to indicate that it would be easier to create a new file through applescript (which should be possible) rather than trying to add content to an existing one... unless you are OK with using a markdown template, which is probably less pretty, but A LOT easier to manipulate...

**Comment by SheriffOfNotts** [comment]
Ok, thanks - makes sense. I will have a look to see how to do it..

**Comment by giovannicoppola** [comment]
try [this](https://github.com/giovannicoppola/Meeting-Notes/blob/main/RTFnotes-for-SheriffOfNotts)  @SheriffOfNotts 🤓
it's suboptimal as I need to write the file to desktop then import it (then delete the intermediate file), but it works 
not tested many events, special characters in the event title might break it because are invalid file names... let me know if you have trouble

**Comment by SheriffOfNotts** [comment]
I've just tried it and it works brilliantly :) Can you let me have a buy you a coffee link? I'd really like to say thank you.

Would you mind removing my name from the code - didn't realise I'd left it in the doc ;)

**Comment by giovannicoppola** [comment]
awesome! happy you found it helpful, and I removed your name :) ... I didn't think anybody would ever find these scripts, I have a few others that I use every day (to snooze emails etc) and I will post them as well.   I am not a professional programmer and I had a lot of help and learned a lot online, so I am happy to pay it forward 🙂

**Comment by SheriffOfNotts** [comment]
Thank you :) Is there any reference guide you used for the table/formatting codes? I feel some more templates coming on lol...

**Comment by giovannicoppola** [comment]
no, I just reverse engineered it by adding text to your template and then opening the RTF raw code to check where the text ended up, and then I replaced it with the strings from the calendar entry ... very low tech

**Comment by SheriffOfNotts** [comment]
I like your style :) 

One thing I would like to change is to put the attendees on a separate line. I previously used "set nameList to nameList & return & name of theName” , but doesn’t seem to work on the new code - any ideas?

**Comment by giovannicoppola** [comment]
`set nameList to nameList & "\\par " & (name of theName)`

**Comment by SheriffOfNotts** [comment]
<img width="836" alt="Screenshot 2021-06-23 at 12 58 36" src="https://user-images.githubusercontent.com/16319499/123093804-02740080-d424-11eb-8030-fbed285841d0.png">

That’s brilliant, thanks Giovanni. Last question :) how do I insert a space before each name (to line up with some other text) or ensure alignment within the table cell? As per the following I am putting the organiser first line of cell then the attendees underneath:

\\f2\\b0 \\cf5 \\cell 
\\pard\\intbl\\itap1\\tx220\\tx720\\pardeftab720\\li720\\fi-720\\sl288\\slmult1\\partightenfactor0
 
\\f2\\b0\\cf2 " & theOrganizer & " (Organiser)
\\f2\\b0 \\

\\pard\\intbl\\itap1\\tx220\\tx720\\pardeftab720\\li720\\fi-720\\sl288\\slmult1\\partightenfactor0
\\f2\\b0 \\cf2 " & nameList & "
\\cell \\lastrow\\row
\\pard\\pardeftab720\\sl288\\partightenfactor0
\\f2\\b0 \\

The output looks like:

I’ve fixed the first line by concatenating a “ “, but it doesn’t work for the following names?

if (ind) = 1 then
				set nameList to nameList & " " & (name of theName)
			else
				set nameList to nameList & " " & ("\\par ") & (name of theName)

**Comment by giovannicoppola** [comment]
have you tried to add the space after the par break, like this:
`set nameList to nameList & ("\\par ") & " " & (name of theName)`

**Comment by SheriffOfNotts** [comment]
Lol, I think I tried every other option :) All working, thanks again..

If I’m not in danger of tipping you over the edge is is possible to change "surname, firstname" to "firstname surname"?

**Comment by giovannicoppola** [comment]
this must be a system setting because for me it is "first name surname" with no comma. I would try to change contact preferences either in outlook or macos

**Comment by SheriffOfNotts** [comment]
Really odd, no setting has any impact. Unbelievably (!) I’ve fixed it using the following:

	set (name of theName) to ((name of theName)'s second word & " " & (name of theName)'s first word)

I will now leave you in peace, thanks again for all your help :)

**Comment by SheriffOfNotts** [comment]
Hi Giovanni, sorry, but my name is still showing although as a change on the code?

BTW what reader did you use for the RTF files any I use show the “\\" as a “\”?

**Comment by giovannicoppola** [comment]
I deleted and replaced the file, let me know if you can still find the name anywhere. I escaped all the backslashes so that the code could be included in an applescript.

**Comment by SheriffOfNotts** [comment]
Thank you. Sorry if I’m being dense, but what do you mean by "I escaped all the backslashes so that the code could be included in an AppleScript.”?

**Comment by giovannicoppola** [comment]
some special characters need to be escaped (i.e. preceded by a `\`) in order to be evaluated literally in code. 
https://www.w3schools.com/python/gloss_python_escape_characters.asp
so `\` became `\\` throughout the RTF code

**Comment by SheriffOfNotts** [comment]
Hi Giovanni, I’ve noticed that the script uses the correct date for individual events, but for reoccurring events it’s using the original scheduled date, not the date of the selected date. 

I’ve tried using the "recurrence ID”, but it just returns “missing value”. “Is recurring” correctly returns “yes”, but I can’t see how to get the correct date.

Any ideas?

Regards.
