### ISSUE TITLE
Script not working for recurring meetings

### ISSUE THREAD

**Issue by SheriffOfNotts** [giovannicoppola/Meeting-Notes#2]
Hi Giovanni, I’ve noticed that the script returns the correct date for individual events, but for reoccurring events it’s returning the first scheduled date of the series, not the date of the selected date.

I’ve tried using the "recurrence ID”, but it just returns “missing value”. “Is recurring” correctly returns “yes”, but I can’t see how to get the correct date.

Any ideas?

Regards.

**Comment by giovannicoppola** [comment]
yes, this seems to be a known issue with outlook recurring events. If you use the script only on the day of the meeting, perhaps it can check if the event is recurring and, if yes, set the current date to the date of the event....You can get [the ID of the recurring event](https://stackoverflow.com/questions/29939779/in-outlook-2011-how-can-i-get-an-occurrence-event-out-of-a-series-using-applesc) relative to a date, so in theory it should be possible to calculate the event date, if you know the ID and the event frequency. I might try to do that when I get a chance... although it seems there is no way to know what day you are on 🙄

**Comment by SheriffOfNotts** [comment]
Thanks Giovanni - glad it’s not me going mad :)

**Comment by SheriffOfNotts** [comment]
Thanks Giovanni, it’s very frustrating - just when I thought it was all working :( I’ve been trying to fix it, but I am beaten..

**Comment by giovannicoppola** [comment]
I tried the script I linked to above and I realized that just the act of getting the occurrence of a calendar event _makes it no longer recurrent_, and after that the script works normally 🤯   so one could get the event ID (which is the first occurrence) and then get the occurrence of the events for a couple of years after the initial date or for the length of the recurrence ... not sure if breaking recurrence has also other effects (I guess if you try to change the series?) so we should test that. I saw your thread on stack exchange, should we move our discussion there? perhaps others will contribute.

**Comment by SheriffOfNotts** [comment]
Interesting.. Thanks Giovanni good idea..

**Comment by giovannicoppola** [comment]
I meant to find a universal solution, but perhaps a partial solution, now, is acceptable. This snippet will deal with recurring events, _but only if run the same day_. This is my use case 99% of the time (I run the script with Alfred right before a meeting), but it might not work for others. Add this snippet at line 24 of the previous script, or use the revised script. Let me know how you get on!

` 
   set isRec to is recurring of calendarEvent

		if isRec = true then
			set tdate to current date
			set sdate to start time of calendarEvent # because current date will have also current time, extract the time from the event (series)
			tell me to set time of tdate to time of sdate
			set myID to id of calendarEvent
			
			
			try
				set calendarEvent to get occurrence of calendar event id myID at tdate
				set eventStart to start time of calendarEvent
				
			on error
				
				display dialog "❗This is a recurrent event, but I see no occurrences on " & tdate with icon 1
				
			end try
		end if
`
